# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/93490e6f-a314-4bd7-a7f3-ba27b5183e2e";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-51d54dea-af3e-44fc-a80a-bafa7bf24ac9".device = "/dev/disk/by-uuid/51d54dea-af3e-44fc-a80a-bafa7bf24ac9";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D241-A901";
      fsType = "vfat";
    };

  zramSwap = {
    enable = true;
    priority = 5;
  };

  swapDevices =
    [ {
      device = "/dev/disk/by-uuid/27a77a05-89ba-46e4-95c7-2452909984f7";
      priority = 4;
    }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
