---
- hosts: localhost

  # TODO: Firefox plugin config?
  tasks:
    - name: Ensure common packages.
      community.general.homebrew:
        name:
          - git
          - pyenv
          - emacs
          - poetry
          - kubectl
          - minikube
          - docker
          - vim
          - terraform
          - stow
        state: present

    - name: Ensure cask packages.
      homebrew_cask:
        name:
          - slack
          - firefox
          - zoom
          - spotify
          - dropbox
        state: present

    - name: Ensure git projects directory.
      ansible.builtin.file:
        path: ~/projects
        state: directory

    - name: Stow dotfiles
      ansible.builtin.command: stow . -v
      args:
        chdir: ~/.dotfiles
      register: stow
      changed_when: stow.stdout != "" or stow.stderr != ""

    - name: Stow stdout
      debug:
        msg: "{{ stow.stdout }}"

    - name: Stow stderr
      debug:
        msg: "{{ stow.stderr }}"


    #- name: Clone a repo with separate git directory
    #  ansible.builtin.git:
    #    repo: https://github.com/ansible/ansible-examples.git
    #    dest: /src/ansible-examples
    #    separate_git_dir: /src/ansible-examples.git
